#+STARTUP: showall

* Software architecture for developers
  :PROPERTIES:
  :ID: 0636920205258-0636920205272
  :icalCategories: 
  :END:
  <2018-08-24 Fri 22:00-01:00> [UTC]

  Location: Online

  The software development industry has made huge leaps in recent
  years; with agile, lean, software craftsmanship, evolutionary design
  and microservices being just a few of the buzzwords we throw around.
  Despite this, software development teams are often more chaotic than
  they are self-organising, with the resulting code being more of a
  mess than was perhaps anticipated.  Successful software projects
  aren't just about good code though, and sometimes you need to step
  away from the IDE for a few moments to see the bigger picture.  This
  training course is about that bigger picture and is aimed at
  software developers who want to learn more about software
  architecture, technical leadership and the balance with agility.
  Join us for a guide to software architecture on modern software
  projects that's pragmatic rather than academic, and lightweight
  rather than "enterprisey".

  Go to the event (https://www.safaribooksonline.com/live-training/courses/software-architecture-for-developers/0636920205258/join/)
